### Updates an existing patient entity
PUT http://lb-01e81558.elb.localhost.localstack.cloud:4004/api/patients/223e4567-e89b-12d3-a456-426614174005
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe UPDATED",
  "email": "john.doe@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}

###